export const ACCOMMODATION_INTRO = {
  title: "Accommodation Options Near the Conference Venue",
  event: "Africa Childcare Forum (ACF) – Mombasa 2026",
  dates: "13 – 15 October 2026",
  venue: "PrideInn Flamingo Beach Resort & Spa, Shanzu, Mombasa",
  forumBlurb:
    "The Second Africa Childcare Forum (ACF Mombasa 2026) is a continental and global co-learning platform accelerating quality, affordable, and inclusive childcare systems across Africa. It will be held at PrideInn Flamingo Beach Resort & Spa, Mombasa, from 13–15 October 2026.",
  summary:
    "The hotels below are all located on or near Serena Road in Shanzu, within easy reach of PrideInn Flamingo Beach Resort & Spa, the ACF conference venue. Delegates can book directly with the hotel of their choice using the email or phone number listed. Rates shown are indicative online rates and change daily — please confirm current pricing and ask about a group rate when booking for ACF. All prices below are per room/person per day, as applicable. USD figures are approximate, converted at ~KES 129.4 = US$1, and will vary slightly with the exchange rate on the day.",
  footnote:
    "Updated, detailed room-type pricing and availability for Kilua Beach Residences, Mombasa Continental Resort, PrideInn Flamingo (venue), PrideInn Paradise, and Royal Shaza Suites is provided in the Hotel Details section below.",
  downloadPath: "/downloads/acf-mombasa-2026-accommodation.pdf",
  downloadName: "ACF-Mombasa-2026-Accommodation.pdf",
};

export const ACCOMMODATION_HOTELS = [
  {
    name: "Kilua Beach Residences by CityBlue",
    distance: "~350m (4–5 min walk)",
    priceLabel: "From KES 14,744 (~US$114)†",
    priceKes: "14,744",
    priceUsd: "114",
    email: "reservations.kilua@citybluehotels.com",
    phone: "+254 790 500900",
    website: "https://www.citybluehotels.com/kilua-residences-by-cityblue",
    image: "/images/hotels/kilua.jpg",
    transport: "Walk",
    details: [
      "Distance from venue: ~350m (4–5 min walk)",
      "Price: From KES 14,744 (~US$114) per night (indicative online rate; ask about a group/corporate rate for ACF delegates)",
      "2-Bedroom Unit: KES 22,000 per night",
      "Meals (if not on a meal plan): Breakfast KES 1,500 | Lunch KES 2,000 | Dinner KES 2,500",
      "Booking email & phone: reservations.kilua@citybluehotels.com | +254 790 500900",
      "Notes: Closest option to the venue. 4-star beachfront aparthotel with pool, spa, gym and conference space — a comfortable, walkable choice for delegates.",
    ],
  },
  {
    name: "Mombasa Continental Resort",
    distance: "~300m (3–4 min walk)",
    priceLabel: "From KES 13,000 (~US$100)†",
    priceKes: "13,000",
    priceUsd: "100",
    email: "reservations@mombasacontinental.com",
    phone: "+254 703 076000",
    website: "https://mombasacontinental.com/",
    image: "/images/hotels/continental.webp",
    transport: "Walk",
    roomRates: [
      { type: "Standard Room", price: "KES 13,000", notes: "Half board" },
      { type: "Deluxe Room", price: "KES 14,500", notes: "Half board" },
      { type: "Superior Room", price: "KES 15,000", notes: "Half board" },
    ],
    details: [
      "Distance from venue: ~300m (3–4 min walk)",
      "Room rates (per night, half board — bed, breakfast & dinner) as in the table below",
      "Booking email & phone: reservations@mombasacontinental.com | +254 703 076000",
      "Notes: 5-star, 175 rooms, on-site conference facilities and direct beach access. One of the closest options and well suited for delegates who want beachfront comfort within walking distance.",
    ],
  },
  {
    name: "PrideInn Flamingo Beach Resort & Spa (Venue)",
    distance: "On-site",
    priceLabel: "KES 18,000 (~US$139)†",
    priceKes: "18,000",
    priceUsd: "139",
    email: "website@prideinn.co.ke",
    phone: "+254 709 532000",
    website: "https://www.prideinnflamingo.com/",
    image: "/images/hotels/flamingo.webp",
    transport: "N/A — venue",
    details: [
      "Distance from venue: On-site — this is the ACF conference venue",
      "Price: KES 18,000 per night, half board (bed, breakfast & dinner), one-bedroom rooms",
      "Availability: 57 one-bedroom rooms currently available",
      "Booking email & phone: website@prideinn.co.ke | +254 709 532000",
      "Notes: Staying at the venue itself — the most convenient option, with zero travel time to sessions. Recommended for delegates who want to book early given limited availability.",
    ],
  },
  {
    name: "PrideInn Paradise Beach Resort & Spa",
    distance: "~750m / 0.3 mi (8–10 min walk)",
    priceLabel: "From KES 20,592 (~US$159)†",
    priceKes: "20,592",
    priceUsd: "159",
    email: "website@prideinn.co.ke",
    phone: "+254 709 532000",
    website: "https://www.prideinn.co.ke/hotels-in-mombasa/prideinn-paradise/",
    image: "/images/hotels/paradise.webp",
    transport: "Walk",
    details: [
      "Distance from venue: ~750m / 0.3 mi (8–10 min walk)",
      "Price: From KES 20,592 (~US$159) per night (indicative online rate; ask about a group/corporate rate for ACF delegates)",
      "Availability: 23 one-bedroom rooms currently available",
      "Booking email & phone: website@prideinn.co.ke | +254 709 532000",
      "Notes: 5-star sister property to the venue, with Africa's largest beach convention centre and a family aqua park. A short, easy walk from PrideInn Flamingo.",
    ],
  },
  {
    name: "Royal Shaza Suites",
    distance: "~0.4 mi / 650m (short walk or quick tuktuk)",
    priceLabel: "From KES 8,500 pp (~US$66)†",
    priceKes: "8,500",
    priceUsd: "66",
    email: "reservations@theroyalshazasuites.co.ke",
    phone: "+254 799 213821",
    website: "https://theroyalshazasuites.co.ke/",
    image: "/images/hotels/royal.jpg",
    contactPerson: "Emmanuel — 0743 621 452",
    transport: "Walk, or short tuktuk",
    roomRates: [
      {
        type: "2-Bedroom Ensuite (shared)",
        price: "KES 8,500 per person",
        notes:
          "Shared by 2 delegates attending the conference; half board; 27 rooms/spaces remaining",
      },
      {
        type: "1-Bedroom (Couples)",
        price: "KES 11,500",
        notes: "Half board; for couples",
      },
      {
        type: "1-Bedroom, 2 Beds (sharing)",
        price: "KES 17,000 total",
        notes: "Half board for both occupants sharing the room",
      },
      {
        type: "3-Bedroom Unit",
        price: "KES 9,500 per person",
        notes: "Half board; for 3 delegates sharing",
      },
    ],
    details: [
      "Distance from venue: ~0.4 mi / 650m (short walk or quick tuktuk)",
      "Contact person: Emmanuel — 0743 621 452",
      "Room rates (per night, half board — bed, breakfast & supper) as in the table below",
      "Booking email & phone: reservations@theroyalshazasuites.co.ke | +254 799 213821 (or contact Emmanuel directly on 0743 621 452)",
      "Notes: 4-star boutique suites on Shanzu Beach Road with 3 pools and a gym. A comfortable, higher-end option within easy reach — walkable, or a quick tuktuk ride if preferred. Now offering competitively priced shared and half-board options for ACF delegates.",
    ],
  },
  {
    name: "Severin Sea Lodge",
    distance: "~2.4km / 1.5 mi",
    priceLabel: "From KES 21,155 (~US$163)",
    priceKes: "21,155",
    priceUsd: "163",
    email: "reservations@severinsealodge.com",
    phone: "+254 746 995690",
    website: "https://www.severinsealodge.com/",
    image: "/images/hotels/severin.jpg?v=2",
    transport: "Tuktuk or matatu",
    details: [
      "Distance from venue: ~2.4km / 1.5 mi",
      "Price: From KES 21,155 (~US$163) per night (indicative online rate; ask about a group/corporate rate for ACF delegates)",
      "Booking email & phone: reservations@severinsealodge.com | +254 746 995690",
      "Notes: 4-star lodge on Bamburi Beach. Too far to comfortably walk with luggage — best for delegates using a tuktuk or matatu daily, or as an overflow option once closer hotels fill up.",
    ],
  },
];

export const ACCOMMODATION_GETTING_THERE = [
  "Delegates staying at Kilua, Mombasa Continental, PrideInn Paradise, Royal Shaza, and other hotels along Serena Road can walk straight to PrideInn Flamingo Beach Resort & Spa — all are within 3–12 minutes on foot.",
  "Tuktuks operate throughout Shanzu and are a quick, inexpensive option for delegates who prefer not to walk, are carrying luggage, or are staying slightly further out.",
  "Matatus run along the main Malindi/Serena Road route and are the most practical option for delegates staying further away, such as those at Severin Sea Lodge on Bamburi Beach.",
  "Delegates should confirm exact walking routes and current tuktuk/matatu fares with hotel front desks, as these change day to day.",
];
